config:
  healthcheck-message: "[]"

spring:
  sql:
    init:
      encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      format_sql: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
    baseline-on-migrate: true
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 50
      maximum-pool-size: 100
      pool-name: SpringBootHikariCP
