config:
  healthcheck-message: "[]"
  auth:
    auth-code-issue-limit-per-day: 10
    auth-code-time-to-live-minute: 3
    auth-code-validated-live-time-minute: 30
  sms:
    driver: file

spring:
  flyway:
    enabled: false

server:
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: false
